version: '3'

services:
  backend:
    image: sshutdownow/kittygram_backend:latest
    container_name: backend
    volumes:
      - media:/app/media
      - backend_static:/app/collected_static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - postgres
    restart: always
    networks:
      - default

  frontend:
    image: sshutdownow/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - frontend_static:/app/build

  gateway:
    image: sshutdownow/kittygram_gateway:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - frontend_static:/var/html/static
      - backend_static:/var/html/backend
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - default

  postgres:
    image: postgres:13.10
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - default

volumes:
  frontend_static:
  backend_static:
  media:
  pg_data: