#cloud-config
ssh_pwauth: no
users:
  - name: ${USER}
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_KEY}"

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ${USER}

write_files:
  - path: "/root/vm_prep.sh"
    permissions: "0755"
    content: |
      #!/bin/sh
      # Опишите установку Docker
      # https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
      # Add Docker's official GPG key:
      sudo apt-get -y update
      sudo apt-get -y install ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      # Add the repository to Apt sources:
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get -y update
      sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      # https://docs.docker.com/engine/install/linux-postinstall/
      sudo systemctl enable docker
      sudo systemctl start docker
      sudo usermod -aG docker ${USER}

runcmd:
  - sleep 1
#  - /root/vm_prep.sh

final_message: "The system is finally up, after $UPTIME seconds"
