name: Terraform
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }} 
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_ssh_key: ${{ secrets.SERVER_SSH_PUBKEY }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

# https://github.com/marketplace/actions/hashicorp-setup-terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.3

    - name: Set up Yandex Cloud service account key
      working-directory: ./infra
      run: |
        echo "${{ secrets.YC_KEY_JSON }}" | base64 -d > ./authorized_key.json

    - name: Initialize Terraform
      working-directory: ./infra
      run: terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Terraform Plan
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'plan' }}
      run: terraform plan
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

### Добавьте сюда стадии для apply и destroy
    - name: Terraform Apply
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        terraform apply -auto-approve
        echo "VM_EXT_IP=$(terraform output -raw external_ip)" >> $GITHUB_ENV
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Set the new IP address for secret SERVER_HOST
      if: ${{ github.event.inputs.action == 'apply' }}
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'SERVER_HOST'
        value: $VM_EXT_IP
        repository: hmanzur/actions-set-secret
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Set the new IP address in tests.yml and commit
      if: ${{ github.event.inputs.action == 'apply' }}
      run: |
        echo 'repo_owner: sshutdownow' > tests.yml
        echo 'kittygram_domain: $VM_EXT_IP' >> tests.yml
        echo 'dockerhub_username: sshutdownow' >> tests.yml        
        git config --global user.name 'Igor Popov'
        git config --global user.email 'IP@users.noreply.github.com'
        git add tests.yml
        git commit -am "Automated commit with the new IP address in tests.yml"
        git push

    - name: Terraform Destroy
      working-directory: ./infra
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform apply -destroy -auto-approve
# https://developer.hashicorp.com/terraform/cli/commands/destroy
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
