name: Terraform
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  - name: Terraform Plan
    working-directory: ./infra
    if: ${{ github.event.inputs.action == 'plan' }}
    run: terraform plan
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
